kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: reporter
  namespace: reporter
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
